image: Ubuntu2004  # образ для сборки

stack: node 18  # окружение

environment:
  GIT_SSH_KEY: $(GIT_SSH_KEY)

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - npx gh-pages -d dist -u "git@github.com:Hav2808/DnD_Homework.git"